wandb_version: 1

env_name:
  desc: null
  value: ned2
Replay_ratio:
  desc: null
  value: 0.2
Success_Standard:
  desc: null
  value: 0.9
policy:
  desc: null
  value: Gaussian
eval:
  desc: null
  value: false
eval_episode:
  desc: null
  value: 3
eval_frequency:
  desc: null
  value: 30
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.005
lr:
  desc: null
  value: 0.0003
alpha:
  desc: null
  value: 0.2
automatic_entropy_tuning:
  desc: null
  value: false
seed:
  desc: null
  value: 123456
hidden_size:
  desc: null
  value: 64
updates_per_step:
  desc: null
  value: 1
target_update_interval:
  desc: null
  value: 1
Is_Clearing_Memory:
  desc: null
  value: true
num_steps:
  desc: null
  value: 1000001
batch_size:
  desc: null
  value: 4096
start_steps:
  desc: null
  value: 10000
max_episode_steps:
  desc: null
  value: 256
time_sleep_interval:
  desc: null
  value: 0.05
average_count_for_successrate:
  desc: null
  value: 20
isExit_IfSuccessLearning:
  desc: null
  value: true
replay_size:
  desc: null
  value: 1000001
state_size:
  desc: null
  value: 10
action_size:
  desc: null
  value: 3
cuda:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715071296.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 61
      4: 3.8.10
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
